# Install VSCode extensions
code --install-extension EditorConfig.EditorConfig
code --install-extension Equinusocio.vsc-material-theme
code --install-extension GrapeCity.gc-excelviewer
code --install-extension MS-CEINTL.vscode-language-pack-fr
code --install-extension PeterJausovec.vscode-docker
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension coolbear.systemd-unit-file
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension mauve.terraform
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-python.python
code --install-extension ms-vscode.atom-keybindings
code --install-extension octref.vetur
code --install-extension sdras.night-owl
code --install-extension sidneys1.gitconfig
code --install-extension wholroyd.HCL
code --install-extension wholroyd.jinja
code --install-extension TabNine.tabnine-vscode